/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentTokenRenewal: typeof import('./components/AgentTokenRenewal.vue')['default']
    BaseChart: typeof import('./components/BaseChart.vue')['default']
    ContainerLogsPanel: typeof import('./components/ContainerLogsPanel.vue')['default']
    GithubBuildCheck: typeof import('./components/GithubBuildCheck.vue')['default']
    GithubObserverSettings: typeof import('./components/GithubObserverSettings.vue')['default']
    ManualReleaseApprovals: typeof import('./components/ManualReleaseApprovals.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerCreationRecovery: typeof import('./components/ServerCreationRecovery.vue')['default']
  }
}
